### PR TITLE
Pin dependencies

### LINKED ISSUE #132: NPM shinkwrap for reviewer
For v2.1.0, reviewer wrote in the email:

> Approving since the xpis could be sufficiently compared, but I've had some major differences between the generated and uploaded xpi. I suspect this is due to differing dependent packages, please consider including an npm-shrinkwrap file next time.

### PR DESCRIPTION
**Pull request by thom4parisot**
Greenkeeper needs to be added as a GitHub integration on https://github.com/integration/greenkeeper

fix #132

### CODE REVIEW

**Comment by DavidBruant** [comment]
> Pin dependencies (...)

Shouldn't dependencies rather be pinned via shrinkwrap?

> (...) and move some to devDependencies

that part of the PR I won't accept because it moves tooling that is compulsory to build the project as devDependency while i believe it should be a dependency imho.

> Add greenkeeper options

I'm fine with the idea of greenkeeper in general, but I'm afraid it'd be more noise than signal. A bunch of people have been vocal recently about it
https://twitter.com/ben_eb/status/822011271734325248
https://twitter.com/sindresorhus/status/830407634557628416

Given the lack of energy I have to spend on Twitter Assistant right now, it'd be more of an annoyance than anything else now. So I'm going to keep this PR around for when I'll have the time. Thanks :-)

**Comment by thom4parisot** [comment]
devDependencies should have been in another pull request I agree.
Although I see `dependencies` as modules necessary for your code to _run_ and `devDependencies`as modules necessary for your project to _build_ and _test_.

It does not matter much if `browserify` is out of date (because devDependencies) unlike `request` which is critical to the safety of the extension at runtime.

I'm quite happy to close this PR and to submit a shrinkwrap one. You won't get a security notice if a dependency is out of date but in the case of extensions, it is likely to be a `{post}test` script to check for security updates or outdates modules.

**Comment by DavidBruant** [comment]
> Although I see dependencies as modules necessary for your code to run and devDependenciesas modules necessary for your project to build and test.

After reading http://stackoverflow.com/a/22004559 i'm convinced by your approach. devDependencies are also for build stuffs. `prepublish` takes care of building before publishing, so build tools aren't necessary to the module users.

**Comment by thom4parisot** [comment]
Yeah exactly.

Another of seeing it is after project is built, when you do `npm prune --production`, the remaining dependencies are the ones needed by your project to actually run.

**Pull request closed without merging**
